import type { Plan } from "@/types";

export const appPlans: Plan[] = [
  {
    id: "app-free",
    product: "app",
    name: "Free",
    tagline: "Empieza a ordenar tu situación tributaria sin costo.",
    priceMonthly: "S/0",
    priceNote: "Gratis para siempre",
    features: [
      "Diagnóstico tributario",
      "10 consultas IA al mes",
      "Asesoría básica",
      "Soporte WhatsApp",
    ],
    ctaLabel: "Comenzar gratis",
    ctaHref: "/contacto",
  },
  {
    id: "app-honorario",
    product: "app",
    name: "Honorario",
    tagline: "Para profesionales que emiten recibos por honorarios.",
    priceMonthly: "S/14.90",
    priceAnnual: "S/99.90",
    priceNote: "al mes · S/99.90 al año",
    features: [
      "Recibos por honorarios",
      "Declaración anual",
      "Dashboard financiero",
      "Consultas IA ilimitadas",
    ],
    ctaLabel: "Elegir Honorario",
    ctaHref: "/contacto",
  },
  {
    id: "app-basico",
    product: "app",
    name: "Básico",
    tagline: "Para quienes manejan boletas y ventas del día a día.",
    priceMonthly: "S/19.90",
    priceAnnual: "S/199.90",
    priceNote: "al mes · S/199.90 al año",
    features: [
      "Boletas",
      "Ventas",
      "Gastos",
      "Declaración SUNAT mensual",
      "Dashboard financiero",
    ],
    ctaLabel: "Elegir Básico",
    ctaHref: "/contacto",
  },
  {
    id: "app-app",
    product: "app",
    name: "App",
    tagline: "El plan completo para tu actividad independiente.",
    priceMonthly: "S/39.90",
    priceAnnual: "S/399.90",
    priceNote: "al mes · S/399.90 al año",
    features: [
      "Facturas y boletas",
      "Ventas y gastos",
      "Declaración mensual",
      "Declaración anual",
      "Alertas SUNAT",
      "Dashboard financiero",
    ],
    highlighted: true,
    badge: "Más popular",
    ctaLabel: "Elegir App",
    ctaHref: "/contacto",
  },
];

export const erpPlans: Plan[] = [
  {
    id: "erp-starter",
    product: "web-saas",
    name: "Starter",
    tagline: "Para empezar a digitalizar tu negocio.",
    priceMonthly: "S/59",
    priceNote: "al mes",
    features: [
      "100 comprobantes al mes",
      "2 usuarios",
      "1 sucursal",
      "Caja POS",
      "Soporte por email",
    ],
    ctaLabel: "Solicitar demo",
    ctaHref: "/contacto",
  },
  {
    id: "erp-emprende",
    product: "web-saas",
    name: "Emprende",
    tagline: "Para negocios en crecimiento que venden cada día.",
    priceMonthly: "S/119",
    priceNote: "al mes",
    features: [
      "300 comprobantes al mes",
      "5 usuarios",
      "2 sucursales",
      "Facturación electrónica",
      "Caja POS e inventario",
      "CRM básico",
      "Soporte por email y chat",
    ],
    ctaLabel: "Solicitar demo",
    ctaHref: "/contacto",
  },
  {
    id: "erp-pyme",
    product: "web-saas",
    name: "Pyme",
    tagline: "Para operaciones con varias sucursales y equipos.",
    priceMonthly: "S/249",
    priceNote: "al mes",
    features: [
      "1000 comprobantes al mes",
      "10 usuarios",
      "5 sucursales",
      "Inventario avanzado",
      "CRM avanzado",
      "Reportes avanzados",
      "Soporte prioritario",
    ],
    highlighted: true,
    badge: "Recomendado",
    ctaLabel: "Solicitar demo",
    ctaHref: "/contacto",
  },
  {
    id: "erp-enterprise",
    product: "web-saas",
    name: "Enterprise",
    tagline: "Para cadenas y empresas con necesidades a medida.",
    priceMonthly: "Desde S/399",
    priceNote: "según requerimiento",
    features: [
      "Comprobantes ilimitados",
      "Usuarios personalizados",
      "Sucursales personalizadas",
      "Módulos personalizados",
      "Integraciones API",
      "Asistente IA",
      "Soporte dedicado",
    ],
    ctaLabel: "Hablar con ventas",
    ctaHref: "/contacto",
  },
];

export const aiCrmAddon = {
  name: "Asistente IA para CRM",
  description:
    "Potencia tu CRM con inteligencia artificial para captar y dar seguimiento a tus clientes de forma automática.",
  priceRange: "Desde S/99 hasta S/150 al mes",
  ctaLabel: "Solicitar implementación",
  features: [
    "Captación de leads",
    "Seguimiento automatizado",
    "Integración con WhatsApp",
    "Chatbot web",
    "Gestión CRM",
  ],
};

export const allPlans: Plan[] = [...appPlans, ...erpPlans];
